/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cimontain;

import java.awt.Desktop;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author Famil
 */
public class Interfaz_Completa1 extends javax.swing.JFrame {

    Connection cn;
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsm;
    DefaultTableModel m;
    DefaultTableModel Tp;
    DefaultTableModel Tv;
    DefaultTableModel Ti;
    DefaultTableModel Tc;
    
    /**
     * Creates new form Interfaz_Completa1
     */
    public Interfaz_Completa1() {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        
        
        
        
        
        
        Tabla_Rea.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
            if(Tabla_Rea.getSelectedRow() != -1){
                int fila = Tabla_Rea.getSelectedRow();
                txtCodigo_P1.setText(Tabla_Rea.getValueAt(fila,0).toString());
            }    
            }
        });
        
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter(){
       @Override
       public void keyPressed(java.awt.event.KeyEvent e){
           if(e.getKeyCode()== KeyEvent.VK_F1){
               jTabbedPane1.setSelectedIndex(0);
           }
           if(e.getKeyCode()== KeyEvent.VK_F2){
               jTabbedPane1.setSelectedIndex(1);
           }
           if(e.getKeyCode()== KeyEvent.VK_F3){
               jTabbedPane1.setSelectedIndex(2);
           }
           if(e.getKeyCode()== KeyEvent.VK_F4){
               jTabbedPane1.setSelectedIndex(4);
           }
       }
       });
        
        jTabbedPane1.setEnabledAt(3,false);
        //jTabbedPane1.setEnabledAt(4,false);
        jTabbedPane1.setEnabledAt(5,false);
        jTabbedPane1.setEnabledAt(6,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Total_L = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaV = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CodeP = new javax.swing.JTextField();
        CantP = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        fecha1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        txtNombre_P = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad_C = new javax.swing.JTextField();
        txtCosto_C = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaC = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo_P = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ComboTipo_P = new javax.swing.JComboBox<>();
        ComboSector_P = new javax.swing.JComboBox<>();
        fecha = new com.toedter.calendar.JDateChooser();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        txtCodigo_P1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCantidad_C1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCosto_C1 = new javax.swing.JTextField();
        fecharea = new com.toedter.calendar.JDateChooser();
        jButton18 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tabla_Rea = new javax.swing.JTable();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_I = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        Tip = new javax.swing.JComboBox<>();
        Clavei = new javax.swing.JTextField();
        Canti = new javax.swing.JTextField();
        acti = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaPrecio = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_C = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton17 = new javax.swing.JButton();
        fechade = new com.toedter.calendar.JDateChooser();
        fechahasta = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane7 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CIMONTAIN");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        jLayeredPane1.setToolTipText("");

        Total_L.setEditable(false);
        Total_L.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Total_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_LActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Total");

        TablaV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaV);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Cantidad");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Codigo servicio");

        CodeP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CodeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodePActionPerformed(evt);
            }
        });

        CantP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CantP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantPActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Siguiente_btn.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        fecha1.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Imprimir_btn.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Cerrar_btn.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(Total_L, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CodeP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CantP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(fecha1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1343, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addComponent(Total_L, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 964, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CodeP, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(CantP))
                        .addGap(64, 64, 64)
                        .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(CodeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CantP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Total_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", jLayeredPane1);

        txtNombre_P.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNombre_P.setPreferredSize(new java.awt.Dimension(12, 20));
        txtNombre_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_PActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Cantidad");

        txtCantidad_C.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCantidad_C.setPreferredSize(new java.awt.Dimension(12, 20));
        txtCantidad_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad_CActionPerformed(evt);
            }
        });

        txtCosto_C.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCosto_C.setPreferredSize(new java.awt.Dimension(12, 20));
        txtCosto_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCosto_CActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Tipo");

        TablaC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TablaC);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Codigo producto");

        txtCodigo_P.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCodigo_P.setPreferredSize(new java.awt.Dimension(12, 20));
        txtCodigo_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo_PActionPerformed(evt);
            }
        });
        txtCodigo_P.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigo_PKeyTyped(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Guardar_btn.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Nombre");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Cerrar_btn.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Costo");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Fecha");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Sector");

        ComboTipo_P.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ComboTipo_P.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicio", "Consumible" }));

        ComboSector_P.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ComboSector_P.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cafeteria", "Ciber" }));

        fecha.setEnabled(false);

        jLayeredPane2.setLayer(txtNombre_P, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtCantidad_C, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtCosto_C, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtCodigo_P, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ComboTipo_P, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ComboSector_P, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(fecha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(87, 87, 87)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCantidad_C, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo_P, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre_P, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(87, 87, 87)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCosto_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboTipo_P, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(ComboSector_P, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad_C, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtCosto_C, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo_P, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel15)
                                                .addComponent(txtNombre_P, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))))
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboSector_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ComboTipo_P, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGap(1, 1, 1)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );

        jTabbedPane1.addTab("Compras", jLayeredPane2);

        txtCodigo_P1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCodigo_P1.setPreferredSize(new java.awt.Dimension(12, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Codigo producto");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Cantidad");

        txtCantidad_C1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCantidad_C1.setPreferredSize(new java.awt.Dimension(12, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Fecha");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Costo");

        txtCosto_C1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCosto_C1.setPreferredSize(new java.awt.Dimension(12, 20));

        fecharea.setEnabled(false);

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Cerrar_btn.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Guardar_btn.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        Tabla_Rea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(Tabla_Rea);

        jLayeredPane6.setLayer(txtCodigo_P1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtCantidad_C1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(txtCosto_C1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(fecharea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jButton18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidad_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(48, 48, 48)
                        .addComponent(txtCodigo_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtCosto_C1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fecharea, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 267, Short.MAX_VALUE)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGap(166, 166, 166))
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fecharea, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCodigo_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)))
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel21)
                                .addComponent(txtCosto_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reabastecimiento", jLayeredPane6);

        Tabla_I.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla_I.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla_I);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Generar_btn.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        Tip.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicios", "Consumibles", "General" }));
        Tip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipActionPerformed(evt);
            }
        });

        Clavei.setEditable(false);
        Clavei.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Canti.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        acti.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        acti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/ACtulizar_btn.png"))); // NOI18N
        acti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actiActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Cerrar_btn.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(Tip, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(Clavei, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(Canti, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(acti, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jButton16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Tip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Clavei, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Canti, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(acti, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1343, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Tip)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Clavei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Canti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acti, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(654, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Inventario", jLayeredPane3);

        TablaPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(TablaPrecio);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Cerrar_btn.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1353, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Precios de Productos", jLayeredPane4);

        Tabla_C.setAlignmentX(2.0F);
        Tabla_C.setAlignmentY(2.0F);
        jScrollPane3.setViewportView(Tabla_C);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Generar_btn.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Exportar_btn.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Ventas", "Compras", "Compras Externas" }));

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cimontain/Diseño/Cerrar_btn.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("De:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Hasta:");

        jLayeredPane5.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jButton4, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane5.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jComboBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jButton17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(fechade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(fechahasta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(595, 595, 595)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fechade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechahasta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechahasta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cierre", jLayeredPane5);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1363, Short.MAX_VALUE)
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Extras", jLayeredPane7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, Short.MAX_VALUE)
        );

        cargartabla_I();
        Auto_cargatabla_C();
        Tabla_Compra();
        Fecha_Actual();
        Auto_Precio_P();
        Auto_V();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        String[] options = new String[]{"Aceptar", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null,"¿Realmente Quiere Salir?","Salir",
            JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, options, options[1]);
        if(option==0){
            this.dispose();
        } 
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            String D = new SimpleDateFormat("yyyy-MM-dd").format(fechade.getDate());
            String H = new SimpleDateFormat("yyyy-MM-dd").format(fechahasta.getDate());
            String rutaArchivo = System.getProperty("user.home")+"/Cierre de "+D+" hasta "+H+".xls";
            File archivoXLS = new File(rutaArchivo);
            if(archivoXLS.exists()) archivoXLS.delete();
            archivoXLS.createNewFile();
            Workbook libro = new HSSFWorkbook();
            FileOutputStream archivo = new FileOutputStream(archivoXLS);
            Sheet hoja = libro.createSheet("Cierre");
            int colum = Tabla_C.getColumnCount();
            int fil = Tabla_C.getRowCount();
            for(int f=0;f<=fil;f++){
                Row fila = hoja.createRow(f);
                for(int c=0;c<colum;c++){
                    Cell celda = fila.createCell(c);
                    if(f==0){
                        celda.setCellValue(Tabla_C.getColumnName(c));
                    }else{
                        celda.setCellValue(Tabla_C.getValueAt(f-1,c).toString());
                    }
                }
            }
            libro.write(archivo);
            archivo.close();
            Desktop.getDesktop().open(archivoXLS);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e,"Advertencia",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cargartabla_C();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String[] options = new String[]{"Aceptar", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null,"¿Realmente Quiere Salir?","Salir",
            JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, options, options[1]);
        if(option==0){
            this.dispose();
        } 
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String[] options = new String[]{"Aceptar", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null,"¿Realmente Quiere Salir?","Salir",
            JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, options, options[1]);
        if(option==0){
            this.dispose();
        } 
    }//GEN-LAST:event_jButton16ActionPerformed

    private void actiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actiActionPerformed
        // TODO add your handling code here:
        String [] registro={Canti.getText(),Clavei.getText()};
        SQL.Actualizar1(registro,"root","","cimontain");
        Canti.setText("");
        Clavei.setText("");
        cargartabla_I();
    }//GEN-LAST:event_actiActionPerformed

    private void TipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        cargartablamanual_I();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String[] options = new String[]{"Aceptar", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null,"¿Realmente Quiere Salir?","Salir",
            JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, options, options[1]);
        if(option==0){
            this.dispose();
        } 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String C = txtCodigo_P.getText();
        if((txtCodigo_P.getText().length()>=9)){
        JOptionPane.showMessageDialog(null,"Exceso de caracteres que se aceptan en Codigo Producto","Advertencia",JOptionPane.WARNING_MESSAGE);
        }else{
        if(C.equals("")){
            String B = new SimpleDateFormat("yyyy-MM-dd").format(fecha.getDate());
            SQL db = new SQL();
            db.MySQLConnection("root", "", "cimontain");
            db.insertData_C_E(txtCantidad_C.getText(), txtCosto_C.getText(),B,txtNombre_P.getText());
            db.In_T_CE(txtCantidad_C.getText(), txtCosto_C.getText(),B,txtNombre_P.getText());
            Tabla_Compra();
            txtCantidad_C.setText("");
            txtCosto_C.setText("");
            txtNombre_P.setText("");
        }else{
            //String B = jDateChooser1.getDateFormatString();

            SQL db = new SQL();
            String B = new SimpleDateFormat("yyyy-MM-dd").format(fecha.getDate());
            db.MySQLConnection("root", "", "cimontain");
            db.insertData_I(txtCodigo_P.getText(),txtNombre_P.getText(),txtCantidad_C.getText(),ComboTipo_P.getSelectedItem().toString(),ComboSector_P.getSelectedItem().toString());
            db.insertData_C(txtCantidad_C.getText(), txtCosto_C.getText(),B,txtCodigo_P.getText());
            db.TC(txtCantidad_C.getText(), txtCosto_C.getText(),B,txtCodigo_P.getText());
            txtCantidad_C.setText("");
            txtCosto_C.setText("");
            txtNombre_P.setText("");
            txtCodigo_P.setText("");
            Tabla_Compra();
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCodigo_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo_PActionPerformed

    private void txtCosto_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCosto_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCosto_CActionPerformed

    private void txtCantidad_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad_CActionPerformed

    private void txtNombre_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_PActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        String[] options = new String[]{"Aceptar", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null,"¿Realmente Quiere Salir?","Salir",
            JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, options, options[1]);
        if(option==0){
            this.dispose();
        } 
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] options = new String[]{"Aceptar", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null,"¿Imprimir Ticket?","Imprimir",
            JOptionPane.NO_OPTION, JOptionPane.CANCEL_OPTION,
            null, options, options[1]);
        if(option==0){
            JOptionPane.showMessageDialog(null, "Impresora GP-5890X No esta Disponible","Error", JOptionPane.ERROR_MESSAGE);
            Auto_V();
            Total_L.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try{
            if((CodeP.getText().length()>=9) && (CantP.getText().length()>=10)){
                JOptionPane.showMessageDialog(null,"Exceso de caracteres en los campos","Advertencia",JOptionPane.WARNING_MESSAGE);
            }else{
            SQL obj = new SQL();
            String consulta  = "Select Inventario.Tipo_P,Precios.Clave_P FROM Precios INNER JOIN Inventario ON Precios.Clave_P=Inventario.Clave_P WHERE Precios.Clave_P='"+CodeP.getText()+"' OR Precios.Clave_Pr='"+CodeP.getText()+"'";
            ResultSet y;
            y = obj.Listar(consulta, "root", "", "cimontain");
            y.next();
            if(y.getString(1).equals("Servicio")){
                String consulta1  = "Select Inventario.Cantidad FROM Precios INNER JOIN Inventario ON Precios.Clave_P=Inventario.Clave_P WHERE Precios.Clave_P='"+CodeP.getText()+"' OR Precios.Clave_Pr='"+CodeP.getText()+"'";
                ResultSet r;
                r = obj.Listar(consulta1, "root", "", "cimontain");
                r.next();
                int menos = Integer.parseInt(CantP.getText());
                int actual = Integer.parseInt(r.getString(1));
                int cambio = actual-menos;
                String [] registro={Integer.toString(cambio),y.getString(2)};
                SQL db = new SQL();
                db.Actualizar1(registro,"root","","cimontain");
                cargartabla_I();
            }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e,"Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        Carga_V();
        Label_Total();
        chequeo();
        CodeP.setText("");
        CantP.setText("");
        
        //chequeo();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void CantPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantPActionPerformed

    private void CodePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodePActionPerformed

    private void Total_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_LActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        if((txtCodigo_P1.getText().length()>=9)){
        JOptionPane.showMessageDialog(null,"Exceso de caracteres que se aceptan en Codigo Producto","Advertencia",JOptionPane.WARNING_MESSAGE);
        }else{
        try{
            SQL obj = new SQL();
            SQL db = new SQL();
            String consulta  = "Select Cantidad FROM Inventario WHERE Clave_P='"+txtCodigo_P1.getText()+"'";
            ResultSet y;
            y = obj.Listar(consulta, "root", "", "cimontain");
            y.next();
            int menos = Integer.parseInt(txtCantidad_C1.getText());
                int actual = Integer.parseInt(y.getString(1));
                int cambio = actual+menos;
                String [] registro={Integer.toString(cambio),txtCodigo_P1.getText()};
        SQL.Actualizar1(registro,"root","","cimontain");
                cargartabla_I();
            String B = new SimpleDateFormat("yyyy-MM-dd").format(fecharea.getDate());
            db.MySQLConnection("root", "", "cimontain");
            db.insertData_C(txtCantidad_C1.getText(), txtCosto_C1.getText(),B,txtCodigo_P1.getText());
            db.TC(txtCantidad_C1.getText(), txtCosto_C1.getText(),B,txtCodigo_P1.getText());
            txtCantidad_C1.setText("");
            txtCosto_C1.setText("");
            txtCodigo_P1.setText("");
            Tabla_Compra();
                
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e,"Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        String[] options = new String[]{"Aceptar", "Cancelar"};
        int option = JOptionPane.showOptionDialog(null,"¿Realmente Quiere Salir?","Salir",
            JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, options, options[1]);
        if(option==0){
            this.dispose();
        } 
    }//GEN-LAST:event_jButton18ActionPerformed

    private void txtCodigo_PKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigo_PKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo_PKeyTyped

    //CArgar Tabla Inventario
    public void cargartabla_I(){
        try{
            String titulos[] = {"Clave Producto","Nombre Producto","Cantidad","Tipo Producto","Secto Producto"};
            Ti = new DefaultTableModel(null,titulos);
            String fila[] = new String[6];
            SQL obj = new SQL();
            String consulta = "SELECT * FROM inventario WHERE Tipo_P='Servicio' OR Tipo_P='Consumible'";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            while (r.next()){
                fila[0] = r.getString(1);
                fila[1] = r.getString(2);
                fila[2] = r.getString(3);
                fila[3] = r.getString(4);
                fila[4] = r.getString(5);
                Ti.addRow(fila);
            }
            Tabla_I.setModel(Ti);
            this.Tabla_I.setModel(Ti);
            Tabla_Rea.setModel(Ti);
            this.Tabla_Rea.setModel(Ti);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    //Cargar tabla inventario manual
    public void cargartablamanual_I(){
        String B=Tip.getSelectedItem().toString();
        if(B.equals("Servicios")){
        try{
            String titulos[] = {"Clave Producto","Nombre Producto","Cantidad","Tipo Producto","Secto Producto"};
            Ti = new DefaultTableModel(null,titulos);
            String fila[] = new String[6];
            SQL obj = new SQL();
            String consulta = "SELECT * FROM inventario WHERE Tipo_P='Servicio'";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            while (r.next()){
                fila[0] = r.getString(1);
                fila[1] = r.getString(2);
                fila[2] = r.getString(3);
                fila[3] = r.getString(4);
                fila[4] = r.getString(5);
                Ti.addRow(fila);
            }
            Tabla_I.setModel(Ti);
            this.Tabla_I.setModel(Ti);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        }
        if(B.equals("Consumibles")){
        try{
            String titulos[] = {"Clave Producto","Nombre Producto","Cantidad","Tipo Producto","Secto Producto"};
            Ti = new DefaultTableModel(null,titulos);
            String fila[] = new String[6];
            SQL obj = new SQL();
            String consulta = "SELECT * FROM inventario WHERE Tipo_P='Consumible'";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            while (r.next()){
                fila[0] = r.getString(1);
                fila[1] = r.getString(2);
                fila[2] = r.getString(3);
                fila[3] = r.getString(4);
                fila[4] = r.getString(5);
                Ti.addRow(fila);
            }
            Tabla_I.setModel(Ti);
            this.Tabla_I.setModel(Ti);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        }
        if(B.equals("General")){
            try{
            String titulos[] = {"Clave Producto","Nombre Producto","Cantidad","Tipo Producto","Secto Producto"};
            Ti = new DefaultTableModel(null,titulos);
            String fila[] = new String[6];
            SQL obj = new SQL();
            String consulta = "SELECT * FROM inventario WHERE Tipo_P='Servicio' OR Tipo_P='Consumible'";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            while (r.next()){
                fila[0] = r.getString(1);
                fila[1] = r.getString(2);
                fila[2] = r.getString(3);
                fila[3] = r.getString(4);
                fila[4] = r.getString(5);
                Ti.addRow(fila);
            }
            Tabla_I.setModel(Ti);
            this.Tabla_I.setModel(Ti);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        }
    }
    
    //Cargar Tabla Cierre Manual
    public void cargartabla_C(){
        String q=jComboBox3.getSelectedItem().toString();
        String D = new SimpleDateFormat("yyyy-MM-dd").format(fechade.getDate());
        String H = new SimpleDateFormat("yyyy-MM-dd").format(fechahasta.getDate());
        if(q.equals("Ventas")){
        try{
            String titulos[] = {"Movimiento","Fecha de Movimiento","Producto o Razon","Cantidad","Precio","Total"};
            m = new DefaultTableModel(null,titulos);
            String fila[] = new String[6];
            SQL obj = new SQL();
            
            String consulta = "SELECT venta.Fecha_V,inventario.Nombre_P,venta.Cantidad_V,precios.Precio_Pr,venta.Cobro_Total_V FROM Venta INNER JOIN Inventario ON Venta.Clave_P=Inventario.Clave_P INNER JOIN Precios ON Inventario.Clave_P=Precios.Clave_P WHERE Venta.Fecha_V BETWEEN '"+D+"' AND '"+H+"'";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            while (r.next()){
                fila[0] = "Venta";
                fila[1] = r.getString(1);
                fila[2] = r.getString(2);
                fila[3] = r.getString(3);
                fila[4] = r.getString(4);
                fila[5] = r.getString(5);
                m.addRow(fila);
            }
            Tabla_C.setModel(m);
            this.Tabla_C.setModel(m);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        }
        if(q.equals("Compras")){
            try{
            String titulos[] = {"Movimiento","Fecha de Movimiento","Producto o Razon","Cantidad","Precio","Total"};
            m = new DefaultTableModel(null,titulos);
            String fila[] = new String[6];
            SQL obj = new SQL();
            String consulta = "SELECT compra.Fecha_C,inventario.Nombre_P,compra.Cantidad_C,Compra.Gasto_C FROM Compra INNER JOIN Inventario ON Compra.Clave_P=Inventario.Clave_P WHERE Compra.Fecha_C BETWEEN '"+D+"' AND '"+H+"'";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            while (r.next()){
                fila[0] = "Compra";
                fila[1] = r.getString(1);
                fila[2] = r.getString(2);
                fila[3] = r.getString(3);
                fila[4] = "";
                fila[5] = r.getString(4);
                m.addRow(fila);
            }
            Tabla_C.setModel(m);
            this.Tabla_C.setModel(m);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        }
                if(q.equals("Compras Externas")){
                    try{
            String titulos[] = {"Movimiento","Fecha de Movimiento","Producto o Razon","Cantidad","Precio","Total"};
            m = new DefaultTableModel(null,titulos);
            String fila[] = new String[6];
            SQL obj = new SQL();
            String consulta = "SELECT compra_ex.Fecha_C,compra_ex.Descripcion,compra_ex.Cantidad_C,compra_ex.Gasto_C FROM compra_ex WHERE Compra_ex.Fecha_C BETWEEN '"+D+"' AND '"+H+"'";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            while (r.next()){
                fila[0] = "Compra Extrena";
                fila[1] = r.getString(1);
                fila[2] = r.getString(2);
                fila[3] = r.getString(3);
                fila[4] = "";
                fila[5] = r.getString(4);
                m.addRow(fila);
            }
            Tabla_C.setModel(m);
            this.Tabla_C.setModel(m);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
                }
                if(q.equals("General")){
                    try{
            String titulos[] = {"Movimiento","Fecha de Movimiento","Producto o Razon","Cantidad","Precio","Total"};
            m = new DefaultTableModel(null,titulos);
            String fila[] = new String[6];
            SQL obj = new SQL();
            String consulta = "SELECT venta.Fecha_V,inventario.Nombre_P,venta.Cantidad_V,precios.Precio_Pr,venta.Cobro_Total_V FROM Venta INNER JOIN Inventario ON Venta.Clave_P=Inventario.Clave_P INNER JOIN Precios ON Inventario.Clave_P=Precios.Clave_P WHERE Venta.Fecha_V BETWEEN '"+D+"' AND '"+H+"'";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            String h = "SELECT compra.Fecha_C,inventario.Nombre_P,compra.Cantidad_C,Compra.Gasto_C FROM Compra INNER JOIN Inventario ON Compra.Clave_P=Inventario.Clave_P WHERE Compra.Fecha_C BETWEEN '"+D+"' AND '"+H+"'";
            ResultSet l;
            l = obj.Listar(h, "root", "", "cimontain");
            String k = "SELECT compra_ex.Fecha_C,compra_ex.Descripcion,compra_ex.Cantidad_C,compra_ex.Gasto_C FROM compra_ex WHERE Compra_ex.Fecha_C BETWEEN '"+D+"' AND '"+H+"'";
            ResultSet u;
            u = obj.Listar(k, "root", "", "cimontain");
            while (r.next()){
                fila[0] = "Venta";
                fila[1] = r.getString(1);
                fila[2] = r.getString(2);
                fila[3] = r.getString(3);
                fila[4] = r.getString(4);
                fila[5] = r.getString(5);
                m.addRow(fila);
            }
            while (l.next()){
                fila[0] = "Compra";
                fila[1] = l.getString(1);
                fila[2] = l.getString(2);
                fila[3] = l.getString(3);
                fila[4] = "";
                fila[5] = l.getString(4);
                m.addRow(fila);
            }
            while (u.next()){
                fila[0] = "Compra Extrena";
                fila[1] = u.getString(1);
                fila[2] = u.getString(2);
                fila[3] = u.getString(3);
                fila[4] = "";
                fila[5] = u.getString(4);
                m.addRow(fila);
            }
            Tabla_C.setModel(m);
            this.Tabla_C.setModel(m);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
                }
    }
    
    //Autocarga de tabla cierre
    public void Auto_cargatabla_C(){
        try{
            String titulos[] = {"Movimiento","Fecha de Movimiento","Producto o Razon","Cantidad","Precio","Total"};
            m = new DefaultTableModel(null,titulos);
            String fila[] = new String[6];
            SQL obj = new SQL();
            String consulta = "SELECT venta.Fecha_V,inventario.Nombre_P,venta.Cantidad_V,precios.Precio_Pr,venta.Cobro_Total_V FROM Venta INNER JOIN Inventario ON Venta.Clave_P=Inventario.Clave_P INNER JOIN Precios ON Inventario.Clave_P=Precios.Clave_P";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            String h = "SELECT compra.Fecha_C,inventario.Nombre_P,compra.Cantidad_C,Compra.Gasto_C FROM Compra INNER JOIN Inventario ON Compra.Clave_P=Inventario.Clave_P";
            ResultSet l;
            l = obj.Listar(h, "root", "", "cimontain");
            String k = "SELECT compra_ex.Fecha_C,compra_ex.Descripcion,compra_ex.Cantidad_C,compra_ex.Gasto_C FROM compra_ex";
            ResultSet u;
            u = obj.Listar(k, "root", "", "cimontain");
            while (r.next()){
                fila[0] = "Venta";
                fila[1] = r.getString(1);
                fila[2] = r.getString(2);
                fila[3] = r.getString(3);
                fila[4] = r.getString(4);
                fila[5] = r.getString(5);
                m.addRow(fila);
            }
            while (l.next()){
                fila[0] = "Compra";
                fila[1] = l.getString(1);
                fila[2] = l.getString(2);
                fila[3] = l.getString(3);
                fila[4] = "";
                fila[5] = l.getString(4);
                m.addRow(fila);
            }
            while (u.next()){
                fila[0] = "Compra Extrena";
                fila[1] = u.getString(1);
                fila[2] = u.getString(2);
                fila[3] = u.getString(3);
                fila[4] = "";
                fila[5] = u.getString(4);
                m.addRow(fila);
            }
            Tabla_C.setModel(m);
            this.Tabla_C.setModel(m);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    
    
     public void Fecha_Actual(){
        DateFormat df = DateFormat.getDateInstance();
        Date FechaActual=new Date();
        fecha.setDate(FechaActual);
        fecha1.setDate(FechaActual);
        fechade.setDate(FechaActual);
        fechahasta.setDate(FechaActual);
        fecharea.setDate(FechaActual);
     }
     
    public void Tabla_Compra(){
        
        try{
            String titulos[] = {"Movimiento","Nombre del Producto","Cantidad","Costo","Fecha de Compra","Tipo","Sector"};
            Tc = new DefaultTableModel(null,titulos);
            String fila[] = new String[7];
            SQL obj = new SQL();
            String consulta = "SELECT Descripcion,Cantidad_C,Gasto_C,Fecha_C FROM Tcompra_ex";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            String h = "SELECT inventario.Nombre_P,tcompra.Cantidad_C,tcompra.Gasto_C,tcompra.Fecha_C,inventario.Tipo_P,inventario.Sector_P FROM tcompra INNER JOIN inventario ON tcompra.Clave_P=inventario.Clave_P";
            ResultSet l;
            l = obj.Listar(h, "root", "", "cimontain");
            while (r.next()){
                fila[0] = "Compra Extrena";
                fila[1] = r.getString(1);
                fila[2] = r.getString(2);
                fila[3] = r.getString(3);
                fila[4] = r.getString(4);
                fila[5] = "";
                fila[6] = "";
                Tc.addRow(fila);
            }
            while (l.next()){
                fila[0] = "Compra";
                fila[1] = l.getString(1);
                fila[2] = l.getString(2);
                fila[3] = l.getString(3);
                fila[4] = l.getString(4);
                fila[5] = l.getString(5);
                fila[6] = l.getString(6);
               Tc.addRow(fila);
            }
            TablaC.setModel(Tc);
            this.TablaC.setModel(Tc);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void Auto_V(){
        String titulos[] = {"Clave Producto","Nombre de Producto","Cantidad","Precio","SubTotal"};
        Tv = new DefaultTableModel(null,titulos);
        TablaV.setModel(Tv);
        this.TablaV.setModel(Tv);
    }
     
    public void Carga_V(){
        try{
        String B = new SimpleDateFormat("yyyy-MM-dd").format(fecha.getDate());
        String fila[] = new String[5];
        SQL obj = new SQL();
        String consulta1  = "Select Precios.Cantidad_D_Pr FROM Precios INNER JOIN Inventario ON Precios.Clave_P=Inventario.Clave_P WHERE Precios.Clave_P='"+CodeP.getText()+"' OR Precios.Clave_Pr='"+CodeP.getText()+"'";
        ResultSet y;
        y = obj.Listar(consulta1, "root", "", "cimontain");
        y.next();
        int desc = Integer.parseInt(y.getString(1));
        int c = Integer.parseInt(CantP.getText());
        if(c<desc){
            String consulta = "SELECT Precios.Clave_Pr,Inventario.Nombre_P,Precios.Precio_Pr,Inventario.Clave_P FROM Precios INNER JOIN Inventario ON Inventario.Clave_P=Precios.Clave_P WHERE Precios.Clave_P='"+ CodeP.getText()+"' OR Precios.Clave_Pr='"+CodeP.getText()+"'";
        ResultSet r;
        r = obj.Listar(consulta, "root", "", "cimontain");
        while (r.next()){
                fila[0] = r.getString(1);
                fila[1] = r.getString(2);
                fila[2] = CantP.getText();
                fila[3] = r.getString(3);
                int k = Integer.parseInt(fila[3]);
                int g = k*c;
                fila[4] = Integer.toString(g);
                Tv.addRow(fila);
                SQL db = new SQL();
                db.MySQLConnection("root", "", "cimontain");
                db.insertData_V(CantP.getText(),Integer.toString(k*c),"0",B,r.getString(4));
            }
        TablaV.setModel(Tv);
            this.TablaV.setModel(Tv);
        }else{
            String consulta = "SELECT Precios.Clave_Pr,Inventario.Nombre_P,Precios.Precio_D_Pr,Inventario.Clave_P FROM Precios INNER JOIN Inventario ON Inventario.Clave_P=Precios.Clave_P WHERE Precios.Clave_P='"+ CodeP.getText()+"' OR Precios.Clave_Pr='"+CodeP.getText()+"'";
            ResultSet r;
            r = obj.Listar(consulta, "root", "", "cimontain");
            while (r.next()){
                fila[0] = r.getString(1);
                fila[1] = r.getString(2);
                fila[2] = CantP.getText();
                fila[3] = r.getString(3);
                int k = Integer.parseInt(fila[3]);
                int g = k*c;
                fila[4] = Integer.toString(g);
                Tv.addRow(fila);
                SQL db = new SQL();
                db.MySQLConnection("root", "", "cimontain");
                db.insertData_V(CantP.getText(),Integer.toString(k*c),"0",B,r.getString(4));
            }
        TablaV.setModel(Tv);
            this.TablaV.setModel(Tv);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void Auto_Precio_P(){
        try{
        String titulos[] = {"Clave Servicio","Nombre de Producto","Cantidad","Precio","Cantidad para Descuento","Precio para Descuento"};
        String fila[] = new String[6];
        Tp = new DefaultTableModel(null,titulos);
        SQL obj = new SQL();
        String consulta = "SELECT Precios.Clave_Pr,Inventario.Nombre_P,Precios.Precio_Pr,Precios.Cantidad_D_Pr,Precios.Precio_D_Pr FROM Precios INNER JOIN Inventario ON Precios.Clave_P=Inventario.Clave_P";
        ResultSet r;
        r = obj.Listar(consulta, "root", "", "cimontain");
        while (r.next()){
                fila[0] = r.getString(1);
                fila[1] = r.getString(2);
                fila[2] = "1";
                fila[3] = r.getString(3);
                fila[4] = r.getString(4);
                fila[5] = r.getString(5);
                Tp.addRow(fila);
            }
        TablaPrecio.setModel(Tp);
        this.TablaPrecio.setModel(Tp);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void Label_Total(){
        double sumatorial=0.0;
        int totalRow=TablaV.getRowCount();
        totalRow-=1;
        for(int i=0;i<=(totalRow);i++)
        {
            double sumatoria= Double.parseDouble(String.valueOf(TablaV.getValueAt(i,4)));
            sumatorial+=sumatoria;
            
            Total_L.setText(""+sumatorial);
        }
    }
    
    public void Precio_P(){
        try{
        String titulos[] = {"Clave Servicio","Nombre de Producto","Cantidad","Precio","Cantidad para Descuento","Precio para Descuento"};
        String fila[] = new String[6];
        Tp = new DefaultTableModel(null,titulos);
        SQL obj = new SQL();
        String consulta = "SELECT Precios.Clave_Pr,Inventario.Nombre_P,Precios.Precio_Pr,Precios.Cantidad_D_Pr,Precios.Precio_D_Pr FROM Precios INNER JOIN Inventario ON Precios.Clave_P=Inventario.Clave_P";
        ResultSet r;
        r = obj.Listar(consulta, "root", "", "cimontain");
        while (r.next()){
                fila[0] = r.getString(1);
                fila[1] = r.getString(2);
                fila[2] = "1";
                fila[3] = r.getString(3);
                fila[4] = r.getString(4);
                fila[5] = r.getString(5);
                Tp.addRow(fila);
            }
        TablaPrecio.setModel(Tp);
        this.TablaPrecio.setModel(Tp);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Obtener los datos","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
}
    
    public void chequeo(){
        try{
            SQL obj = new SQL();
            String consulta3  = "Select Inventario.Cantidad FROM Inventario INNER JOIN Precios ON Precios.Clave_P=Inventario.Clave_P WHERE Precios.Clave_P='"+CodeP.getText()+"' OR Precios.Clave_Pr='"+CodeP.getText()+"'";
            ResultSet yy;
            yy = obj.Listar(consulta3, "root", "", "cimontain");
            yy.next();
            int ca = Integer.parseInt(yy.getString(1));
            if(ca==0){
                JOptionPane.showMessageDialog(null, "Ya NO Tienes Mas de Estos Productos","Advertencia",JOptionPane.WARNING_MESSAGE);
            }else{
                if(ca>=1 && ca<=5){
                JOptionPane.showMessageDialog(null, "Estan Por Acabarse Estos Productos","Advertencia",JOptionPane.WARNING_MESSAGE);
            }
            }    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e,"Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Completa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Completa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Completa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Completa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Completa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantP;
    private javax.swing.JTextField Canti;
    private javax.swing.JTextField Clavei;
    private javax.swing.JTextField CodeP;
    private javax.swing.JComboBox<String> ComboSector_P;
    private javax.swing.JComboBox<String> ComboTipo_P;
    private javax.swing.JTable TablaC;
    private javax.swing.JTable TablaPrecio;
    private javax.swing.JTable TablaV;
    private javax.swing.JTable Tabla_C;
    private javax.swing.JTable Tabla_I;
    private javax.swing.JTable Tabla_Rea;
    private javax.swing.JComboBox<String> Tip;
    private javax.swing.JTextField Total_L;
    private javax.swing.JButton acti;
    private com.toedter.calendar.JDateChooser fecha;
    private com.toedter.calendar.JDateChooser fecha1;
    private com.toedter.calendar.JDateChooser fechade;
    private com.toedter.calendar.JDateChooser fechahasta;
    private com.toedter.calendar.JDateChooser fecharea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCantidad_C;
    private javax.swing.JTextField txtCantidad_C1;
    private javax.swing.JTextField txtCodigo_P;
    private javax.swing.JTextField txtCodigo_P1;
    private javax.swing.JTextField txtCosto_C;
    private javax.swing.JTextField txtCosto_C1;
    private javax.swing.JTextField txtNombre_P;
    // End of variables declaration//GEN-END:variables
}
